php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - PHALCON_VERSION="2.0.x"
  - PHALCON_VERSION="phalcon-v2.0.2"
  - PHALCON_VERSION="phalcon-v2.0.1"
  - PHALCON_VERSION="phalcon-v2.0.0"

services:
  - mongodb
  - memcached

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS vegas_test;" -uroot

before_script:
  - travis/install-php-extension.sh ${PHALCON_VERSION}
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - composer self-update
  - composer update
  
script:
  - cp tests/config.sample.php tests/config.php
  - mkdir -p tests/fixtures/cache
  - mkdir -p tests/fixtures/tmp
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
